name: Build and Package

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs_version: '2019'  # 指定 VS 版本

      - name: Set up MSVC build tools
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64
          set > vars.txt
          echo "PATH: %PATH%" >> vars.txt
          type vars.txt

      - name: Check nmake
        run: where nmake || echo "nmake not found"

      - name: Run Ant Build
        run: |
          cd src/main/native
          ant -Djni.cc=cl -Djni.make=nmake -Djni.makefile=Makefile.win32 all
