name: Build and Package

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC build tools
        run: |
          cmd /c "\"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat\" amd64"

      - name: Output environment variables
        run: |
          cmd /c "set > env_vars.txt"
          cmd /c "echo PATH: %PATH% >> env_vars.txt"
          cmd /c "type env_vars.txt"

      - name: Check nmake
        run: cmd /c "where nmake || echo nmake not found"

      - name: Run Ant Build
        run: |
          cd src/main/native
          ant -Djni.cc=cl -Djni.make=nmake -Djni.makefile=Makefile.win32 all
