name: Build with nmake

on:
  push:
    branches:
      - master  # 或其他你想要触发构建的分支
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境进行构建

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Visual Studio
        uses: actions/setup-msbuild@v1
        with:
          vs-version: 'latest'  # 或指定具体版本，如 '2019'

      - name: Build with nmake
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86  # 根据需要调整路径和架构
          cd src/main/native
          nmake -f Makefile.win32  # 使用指定的 Makefile 进行构建
